keys:
  - &nixtop age1qg2xu2fhr2jn9mtxah5x5v9laj9lexc555lvqh22tw04d9plw3qs4l74gz
  # - &nixos age1dyqlg23gm64qpa8usqujr5kd26tgwhahg0ngsclpnn0q2ada3qpqqg8yll
  - &matatan_mbp age10vhkpj4xuzx644dy65d8lygp4y0jfuzm0ru03vklnwzk493avvmqk5gyd3

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *nixtop
          # - *nixos
          - *matatan_mbp
